version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
      args:
        - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    container_name: telegram-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - bot-network
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep python | grep renum_telebot.py || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  watchdog:
    build:
      context: .
      dockerfile: Dockerfile.watchdog
    container_name: bot-watchdog
    restart: unless-stopped
    depends_on:
      bot:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - bot-network
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    env_file:
      - .env

networks:
  bot-network:
    name: bot-network